#!/usr/bin/env escript

main([Port]) ->
	{ok, _} = game_sup:start_link(),
	{ok, _} = player_sup:start_link(list_to_integer(Port)),
	receive stop -> ok end;

main(_) ->
	io:format("usage: ./serv499 <port>\n"),
	ok.
